### ISSUE TITLE
Check initialization executes numerous calls to determine the Priority and Checktype of a plugin which slows down overall execution

### ISSUE THREAD

**Issue by k-simons** [palantir/okgo#326]
- Currently we invoke plugin.Type() and plugin.Priority many times though the invocation of the main check command
- Under the hood, this works by delegating out to the plugin executable and serializing the result back
- Although these are fast independently, they can slowly add up as the number of plugins added to a project grows. This is particularly bad because we sort the plugins which relies on both of these values
- We should just invoke the plugin a single time to get the type and priority and use if for the lifecycle of the check command
- This fix will have 2 parts

**Comment by nmiyake** [comment]
Thanks for investigating -- out of curiosity, have you actually timed the overhead this causes/observed a noticeable diff by cutting down these calls? As you point out here, part of the initial assumption was that these were local calls with serialized bodies that weren't too large, and even for "lots" of plugins, I would still assume the number is in the 10s (<100), so am kind of surprised that this would show up as a bottleneck.

**Comment by k-simons** [comment]
This is fixed now
